### PR TITLE
Update tt_reboot with new reset command to make it work again

### PR DESCRIPTION
**Pull request by Grimler91**
Tested on v2 device, watch sort of hangs and then reboots as when attaching charging cable.

### CODE REVIEW

**Comment by Grimler91** [comment]
Also closes #10.

**Comment by dlenski** [comment]
Nice. This should be made one of the "virtual functions" that can differ between v1 and v2 devices … unless you can verify that this works on v1 also?

**Comment by Grimler91** [comment]
Would you like a dummy function that perhaps just prints a message about reboot being un-supported for v1 devices? The current overload implementation doesn't work for v1 either so we might just as well remove it. 

I should be able to try this new tt_reboot implementation with a v1 device during the upcoming Christmas holiday. Can add a switch in tt_reboot for now

**Comment by dlenski** [comment]
> The current overload implementation doesn't work for v1 either so we might just as well remove it.

It doesn't…?

It worked on my old Runner v1 (which was the guinea pig with which it was written) but I no longer have that device.

**Comment by Grimler91** [comment]
> It doesn't…?

Hrm, I think I tested it on both versions before opening #10, but I see now that I haven't written any note about that in #10 so I might be wrong. I'll test it when I get the chance.

I've update the PR so that the overload code is used for v1 devices. 
Should I also remove the warning added in https://github.com/dlenski/ttblue/commit/31e9e8df9899c4157b9af62752dc5cb7bbc0e456?

**Comment by dlenski** [comment]
Gotcha, thanks. I made a slightly less redundant version that also does the looping for v2 devices (can't hurt, can it?).

I think the warning should probably stay since this is voodoo and we _don't_ actually know that it works on devices+firmware versions beyond those that we've actually tested.

**Comment by Grimler91** [comment]
Reboot works with your update as well (so doesn't seem to hurt)!

> I think the warning should probably stay since this is voodoo and we don't actually know that it works on devices+firmware versions beyond those that we've actually tested.

That's true. Testing older versions of the firmware feels hard though, since it would require flashing old firmware versions to the watch, and the older firmware might be hard to obtain. Do we want to support/try to support older firmware versions or is it perhaps more reasonable to only support the latest firmware available for all watch versions?

**Comment by dlenski** [comment]
> Reboot works with your update as well (so doesn't seem to hurt)!

:+1: 

> Testing older versions of the firmware feels hard though, since it would require flashing old firmware versions to the watch, and the older firmware might be hard to obtain. Do we want to support/try to support older firmware versions or is it perhaps more reasonable to only support the latest firmware available for all watch versions?

Yes, it is a time-consuming pain to try to support older versions.

Generally, what I try to do for software like this where I'm interacting with new versions of a "black box" (some device firmware or program for which I don't have any access to the internals), is that I try to verify support for newer versions, but make changes to my code _cautiously_ to try to avoid _unnecessarily_ disrupting functionality that continues to work with an old version of the "black box."

**Comment by Grimler91** [comment]
I see, noted. I'll adopt that philosophy for future PRs :+1:

**Pull request merged**
